FROM gcr.io/world-fishing-827/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8

RUN apt-get update && \
    apt-get -qy install gdal-bin libgdal-dev && \
    export GDAL_VERSION="$(gdal-config --version)"

# Setup scheduler-specific dependencies
COPY ./requirements-scheduler.txt ./
RUN pip install -r requirements-scheduler.txt

# Setup worker-specific dependencies
COPY ./requirements-worker.txt ./
RUN pip install -r requirements-worker.txt

# # Setup local package
# COPY . /opt/project
# RUN pip install -e .

# Setup local packages
COPY . /opt/project
ENV PYTHONPATH /opt/project
RUN cd /usr/local/lib/python3.8/site-packages && \
    python /opt/project/setup.py develop

# Setup the entrypoint for quickly executing the pipelines
ENTRYPOINT ["./main.py"]
