# Query parameters:
bq_in_named_anchorages: "world-fishing-827.anchorages.named_anchorages_v20201104"
bq_in_messages: "world-fishing-827.pipe_ais_v3_internal.messages_positions"
bq_out_port_state_transitions: "world-fishing-827.scratch_tomas_ttl30d.port_visit_msgs"
start_date: "2018-01-01"
end_date: "2018-01-07"

# Apache Beam / Dataflow options:
job_name: porteventstest
project: world-fishing-827
runner: DataflowRunner
max_num_workers: 100
disk_size_gb: 100
region: us-central1
staging_location: "gs://machine-learning-dev-ttl-30d/anchorages/portevents/output/staging"
temp_location: "gs://machine-learning-dev-ttl-30d/anchorages/temp"
setup_file: "./setup.py"
sdk_container_image: "gcr.io/world-fishing-827/pipe-anchorage/worker:tim_test"
experiments: ["use_runner_v2"]

# Labels for cost tracking (label values: lowercase letters, digits, '_' and '-').
labels:
  environment: development
  resource_creator: tomas-link
  project: ais
  stage: anchorages
