# Query parameters:
bq_in_port_visits: "global-fishing-watch.pipe_ais_v3_published.port_visits"
min_confidence: "3"
bq_out_voyages: "world-fishing-827.scratch_tomas_ttl30d.voyages_c3"

# General parameters:
project: world-fishing-827
